<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/courses.php");
	include("$currDir/courses_dml.php");

	

	if($render) $x->Render();

	// hook: courses_header
	$headerCode='';
	if(function_exists('courses_header')){
		$args=array();
		$headerCode=courses_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	
?>

  <html>
	<body>

	<br>
	<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Staff</button>
	<br>
	<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog">
	  
		  <!-- Modal content-->
		<div class="modal-content">
		 <div class="modal-header">
		  <button type="button" class="close" data-dismiss="modal">&times;</button>
		  <h4 class="modal-title">Staff</h4>
		</div>
		  
	<div class="modal-body">
	  <form action="courses_view.php" method="POST">
		<div class="form-group">
		  <label for="name">Officials FullName:</label>
		  <input type="name" class="form-control" id="fullname" placeholder="Enter fullname" name="fullname" required>
		</div>
		<div class="form-group">
		  <label for="mobile">Mobile:</label>
		  <input type="mobile" class="form-control" id="mobile" placeholder="Enter mobile" name="mobile" required>
		</div>
			<div class="form-group">
		  <label for="address">Age:</label>
		  <input type="address" class="form-control" id="age" placeholder="age" name="age" required>
		</div>
		
		
		  <label for="name">Gender:</label>
		  <input type="name" class="form-control" id="gender" placeholder="gender" name="gender">
		</div>
		<div class="form-group">
		  <label for="name">Address:</label>
		  <input type="name" class="form-control" id=address" placeholder="address" name="address">
		</div>
		
		     <div class="form-group">
		  <label for="name">Civil Status:</label>
		  <input type="name" class="form-control" id="civil" placeholder="Civil Status" name="civil

			 <div class="form-group">
		  <label for="address">Citizenship</label>
		  <input type="address" class="form-control" id="citizenship" placeholder="Citizenship" name="citizenship" required>
		</div>
		
		     <div class="form-group">
		  <label for="name">Date of Birth:</label>
		  <input type="name" class="form-control" id="dob" placeholder="Date of Birth" name="dob">
		</div>
		
		      <div class="form-group">
		  <label for="name">Place of Birth:</label>
		  <input type="name" class="form-control" id="pob" placeholder="Date of Birth" name="pob">
		</div>
		
	
		
		
		
		<div>
		<button type="submit" class="btn btn-default" id="submit" name="submit2">Submit</button>
		</div>
		</form>
		</div>
		</div>
		</div>
		
		<link href="js/bootstrap.min.css" rel="stylesheet">


		  <div class="container" style="margin-top:35px">
			<div class="form-group">
				<select name="state" id="maxRows" class="form-control" style="width:150px;">
					<option value="5000">Show All</option>
					<option value="5">5</option>
					<option value="10">10</option>
					<option value="15">15</option>
					<option value="20">20</option>
					<option value="50">50</option>
					<option value="75">75</option>
					<option value="100">100</option>
				</select>
			</div>
			
			
			<?php

			include ('connection.php');
			$show = mysqli_query($conn,"SELECT * FROM tbl_staff");        
					
			if(mysqli_num_rows($show)>0){
			
			echo "<form method='POST' action='courses_view.php'>";
			echo "<table id='mytable' class='table table-bordered table-striped'>";
			echo "<thead>";
							echo "<tr>";
							echo "<th>Officials FullName</th>";
							echo "<th>Mobile</th>";
							echo "<th>Age</th>";
							echo "<th>Address</th>";
							echo "<th>Civil Status</th>";
							echo "<th>Citizenship</th>";
							echo "<th>Date of Birth</th>";
							echo "<th>Place of Birth</th>";
							echo "<th>Gender</th>";
							echo "</tr>";
			echo "</thead>";
			echo "<tbody>";
							while($row=mysqli_fetch_array($show)){
								echo "<tr>";
								echo "<td>".$row[1]."</td>";
								echo "<td>".$row[2]."</td>";
								echo "<td>".$row[3]."</td>";
								echo "<td>".$row[4]."</td>";
								echo "<td>".$row[5]."</td>";
								echo "<td>".$row[6]."</td>";
								echo "<td>".$row[7]."</td>";
								echo "<td>".$row[8]."</td>";
								echo "<td>".$row[9]."</td>";
								$userid = $row[0];
								echo "<td><input type='submit' value='View' name='btnview".$userid."'>&nbsp<input type='submit' value='Delete' name='btndelete".$userid."'></td>";
								echo "</tr>";
							}
			  echo "</tbody>";
				echo "</form>";
			echo "</table>";

							
		}


					else{
						echo "No records found";
					}
					
	if(isset($_POST['btndelete'.$userid])){

				   include 'connection.php';

					$qry = "DELETE FROM tbl_staff where staff_id = '$userid'";  
					mysqli_query($conn, $qry)   or die (mysqli_error($conn));
				echo "<script type='text/javascript'>
				alert('Item deleted!');
				window.location='courses_view.php';
				</script>";
	}

					
	if(isset($_POST["submit2"])){

	$id = $row['staff_id'];
	$fullname = $_POST["fname"];
	$mobile = $_POST["mobile"];
	$age = $_POST["age"];
	$gender = $_POST["gender"];
	$address = $_POST["address"];
	$civil = $_POST["civil"];
	$citizenship = $_POST["citizen"];
	$dob = $_POST["dob"];
	$pob = $_POST["pob"];

	$query = "INSERT INTO tbl_staff(staff_id,fname,mobile,age,gender,address,civil,citizen,dob,pob) VALUES ('$staff_id''$fullname','$mobile','$age','$gender','$address','$civil','$citizenship','$dob','$pob',');";
		
	mysqli_query($conn, $query) or die (mysqli_error($conn));

		 echo "<script type='text/javascript'>
				alert('Added successfully!');
				window.location='courses_view.php';
				</script>";

	}


	if(isset($_POST['btnview'.$userid])){

				   include 'connection.php';

					$selectdata = mysqli_query($conn, "SELECT * FROM tbl_staff where staff_id = '$userid'");

					$row = mysqli_fetch_array($selectdata);
					
			echo "<html>
					<body>
					<div id='printModal' class='modal fade' role='dialog'>
	  <div class='modal-dialog'>
	  
		  <!-- Modal content-->
		<div class='modal-content'>
		  <div class='modal-header'>
			<button type='button' class='close' data-dismiss='modal'>&times;</button>
			<h4 class='modal-title'>Print Preview</h4>
		  </div>
		  <div class='modal-body'>
		
	<table class='table table-bordered'>
	  <thead>
		<tr>
		  <th>Complainant Full Name</th>
		  <th>Address</th>
		  <th>".$row['address']."</th>
		</tr>
	  </thead>
	  <tbody>
		<tr>
		  <td>".$row['cpfname']."</td>
		  <td>Age</td><td>".$row['age']."</td>
		</tr>
		<tr>
		<th scope='row'>Type of complain</th>
		  <td>".$row['toc']."</td>
		  <td scope='row'>Time</td><td>".$row['time']."</td>
		</tr>
		<th>Witness</th>
		<td>".$row['weatness']."</td>
		<th>Brgy official duty</th>
		<td>".$row['bod']."</td>
		<tr>
		<th>Complainee Full Name</th>
		<td>".$row['cf']."</td>
		<th>Mobile</th>
		<td>".$row['mobiles']."</td>
		</tr>
		<th>Witness</th>
		<td>".$row['weatness']."</td>
		<th>Address</th>
		<td>".$row['adds']."</td>
		<tr>
		<th>Age</th>
		<td>".$row['ages']."</td>
		</tr>
		</tbody>
		</table>

		</div>
		  <div class='modal-footer'>
			<button type='button' class='btn btn-default' data-dismiss='modal'>Print</button>
		  </div>
		</div>
		</div>
		</div>
		</body>
		</html>
		<script>$('#printModal').modal('show')</script>";			
			}	


				?>
					
	</body>
	</html>